server:
    port: 8080
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/study_security_oauth2?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
        username: root
        password: 123456
        hikari:
            maximum-pool-size: 20
            minimum-idle: 10
    application:
        name: auth-service # 应用名称

eureka:
  client:
    service-url: # EurekaServer地址
      defaultZone: http://127.0.0.1:10086/eureka
      #defaultZone: http://127.0.0.1:10086/eureka,http://127.0.0.1:10087/eureka #因为EurekaServer不止一个，因此注册服务的时候，service-url参数需要变化：
  instance:
    prefer-ip-address: true # 当调用getHostname获取实例的hostname时，返回ip而不是host名称
    ip-address: 127.0.0.1 # 指定自己的ip信息，不指定的话会自己寻找
    #服务续约:这两个值在生产环境不要修改，默认即可。但是在开发时，这个值有点太长了，经常我们关掉一个服务，会发现Eureka依然认为服务在活着。所以我们在开发阶段可以适当调小。
    lease-expiration-duration-in-seconds: 10 # 10秒即过期, 默认90秒
    lease-renewal-interval-in-seconds: 5 # 5秒一次心跳, 默认30秒
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}

